[metadata]
name = agrobot_plc_bridge
version = 0.0.1

[options]
packages = find:
install_requires = setuptools

[options.data_files]
share/ament_index/resource_index/packages =
    resource/agrobot_plc_bridge
share/agrobot_plc_bridge =
    package.xml
share/agrobot_plc_bridge/launch =
    launch/plc_bridge.launch.py
share/agrobot_plc_bridge/config =
    config/plc_bridge.yaml

[options.entry_points]
console_scripts =
    plc_bridge = agrobot_plc_bridge.plc_bridge:main

[develop]
script_dir=$base/lib/agrobot_plc_bridge

[install]
install_scripts=$base/lib/agrobot_plc_bridge
